environment:

  matrix:
    - TARGET_ARCH: x86
      CONDA_PY: 2.7
      CONDA_INSTALL_LOCN: C:\\Miniconda

    - TARGET_ARCH: x64
      CONDA_PY: 2.7
      CONDA_INSTALL_LOCN: C:\\Miniconda-x64

    - TARGET_ARCH: x86
      CONDA_PY: 3.5
      CONDA_INSTALL_LOCN: C:\\Miniconda35

    - TARGET_ARCH: x64
      CONDA_PY: 3.5
      CONDA_INSTALL_LOCN: C:\\Miniconda35-x64

    - TARGET_ARCH: x86
      CONDA_PY: 3.6
      CONDA_INSTALL_LOCN: C:\\Miniconda36

    - TARGET_ARCH: x64
      CONDA_PY: 3.6
      CONDA_INSTALL_LOCN: C:\\Miniconda36-x64


# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
    - x64

install:
    # If there is a newer build queued for the same PR, cancel this one.
    - cmd: |
        powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py', 'ff_ci_pr_build.py')"
        ff_ci_pr_build -v --ci "appveyor" "%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_SLUG%" "%APPVEYOR_BUILD_NUMBER%" "%APPVEYOR_PULL_REQUEST_NUMBER%"
        del ff_ci_pr_build.py

    # Cywing's git breaks conda-build. (See https://github.com/conda-forge/conda-smithy-feedstock/pull/2.)
    - cmd: rmdir C:\cygwin /s /q

    # Force input and output streams to flush immediately.
    # Also use binary mode, which is sometimes needed on Windows.
    - cmd: set PYTHONUNBUFFERED=1

    # AppVeyor gives us 2 cores to work with.
    #
    # ref: https://www.appveyor.com/docs/build-environment/#build-vm-configurations
    - cmd: set CPU_COUNT=2

    # Use a small path for conda-build's working directory.
    - cmd: set "CONDA_BLD_PATH=C:\\bld\\"

    # Add path, activate `conda` and update conda.
    - cmd: set "PATH=%CONDA_INSTALL_LOCN%\\Scripts;%CONDA_INSTALL_LOCN%\\Library\\bin;%PATH%"
    - cmd: conda update --yes --quiet conda
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat

    # Configure conda.
    - cmd: conda config --set show_channel_urls true
    - cmd: conda config --set auto_update_conda false
    - cmd: conda config --set add_pip_as_python_dependency false

    # Update and install everything.
    - cmd: conda update --all --quiet --yes
    - cmd: conda install --quiet --yes jinja2 conda-build

    # Patch VS 2008 for 64-bit support.
    - cmd: conda install -c conda-forge --no-update-deps --quiet --yes vs2008_express_vc_python_patch
    - cmd: call setup_x64

    # Show info about conda install.
    - cmd: conda info
    - cmd: conda config --get

    # Create the test environment.
    - cmd: conda create -y -n testenv python="%CONDA_PY%"
    - cmd: conda env update -n testenv --file environment_ci.yml
    - cmd: activate testenv

# Skip .NET project specific build phase.
build: off

test_script:
    # command to run tests, e.g. python setup.py test
    - cmd: coverage erase
    - cmd: coverage run --append --source . setup.py --version
    - cmd: coverage run --append --source . setup.py test
    - cmd: coverage report -m
